### ISSUE TITLE
Leaked API key through chrome dev tools

### ISSUE THREAD

**Issue by Reynadi531** [sozonome/muvees#3]
![image](https://user-images.githubusercontent.com/43875921/117642607-afb2f200-b1b1-11eb-8d6e-9212556c156f.png)

Hai,
 
Gw lagi liat liat portofolio lu dan iseng iseng buka dev tools di "muvees". Dari request yang keluar ada api key leaked. Kalo itu jadi concern mungkin boleh coba bikin proxy REST API as wraper API nya dengan cors disable, atau mungkin coba GetServerSideProps / GetInitialProps dari nextjs.

Best Regards,
Rey

**Comment by sozonome** [comment]
Hello @Reynadi531 thank you for the advice

Actually I build this project with being okay if the api key is leaked in mind, because it's just a fun project. Usually I'll wrap it so the api key won't be shown.

Will try to make an api wrapper for this project.

**Comment by Reynadi531** [comment]
Thank you. I really apreciate your taking time to reply my issue. Have a nice day, cheers.
